#!/bin/bash
echo yaourt --noconfirm -Syua
yaourt --noconfirm -Syua
if [ -n "$(sudo find /etc -name "*pacnew" -print -quit)" ] # -n is true if string has length
then
	echo
	echo yaourt -C
	yaourt -C
else
	exit 1
fi
echo
echo _____________________
echo Hit Enter to continue
read
